mainapp/urls.py
from django.urls import path

from mainapp.views import UserLoginView, logout_user, SchemasView, CreateSchemaView, EditSchemaView, SchemaDataSets, \
    download, delete_schema, generate_data_set, get_finished_data_sets_info, UserRegisterView

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('', SchemasView.as_view(), name='schema-list'),
    path('create-schema/', CreateSchemaView.as_view(), name='create-schema'),
    path('edit/<slug:schema_slug>/', EditSchemaView.as_view(), name='edit-schema'),
    path('data-sets/<slug:schema_slug>/', SchemaDataSets.as_view(), name='schema-data-sets'),
    path('download/', download, name='download'),
    path('delete-schema/', delete_schema, name='delete-schema'),
    path('start-generating/', generate_data_set, name='data-set-start-generating'),
    path('get-finished-data-sets-info/', get_finished_data_sets_info, name='get-finished-data-sets-info'),
]

schemas/urls.py
from django.contrib import admin
from django.urls import path, include

from schemas import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

# if settings.DEBUG:
#     urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

mainapp/models.py
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse
from django_extensions.db.fields import AutoSlugField
from django.contrib.auth.models import User

from .data_generators.data_generators import CellDataGenerator, RowDataGenerator
from .data_generators.file_generation import generate_csv_file


class Column(models.Model):
    """
    Represents column in schema.

    If you want to add new type of data for generating, you should:
        1. Add name of data type and short version of name (3 chars) to inner class DataType, likewise present.
        2. Add function for generating data to file data_generation.py in package data_generators.
            2.1 If your data type have limits (minimal and maximal), function should take these parameters.
            2.2 If your data type uses source data for generating - function should take this source data lists as
            arguments, named as source data types.
        3. If your data type have limits, you also should add it to LIMITED_DATA_TYPES collection below.
        4. If your data type uses source data, you also should:
            4.1 Add it to DATA_TYPE_SOURCE_TYPES dictionary below as key, with value of list with source data types.
            4.2 Add this data to data base via model SourceData using one of methods - manage.py shell,
                admin of the site, or load from json file using command "load_data_source" (in this case json file must
                contain dictionary, where keys are source data types,
                and values are lists of data options for generating).

    """

    class DataType(models.TextChoices):
        INTEGER = "INT"
        FULL_NAME = "FNM"
        JOB = "JOB"
        EMAIL = "EML"
        DOMAIN_NAME = "DMN"
        PHONE_NUMBER = "PHN"
        COMPANY_NAME = "CMN"
        TEXT = "TXT"
        ADDRESS = "ADR"
        DATE = "DTE"

    LIMITED_DATA_TYPES = (DataType.INTEGER, DataType.TEXT)
    DATA_TYPE_SOURCE_TYPES = {DataType.FULL_NAME: ["first_names", "last_names"], DataType.JOB: ["jobs"]}

    name = models.CharField(max_length=64)
    minimal = models.PositiveSmallIntegerField(blank=True, null=True)
    maximal = models.PositiveSmallIntegerField(blank=True, null=True)
    data_type = models.CharField(max_length=3, choices=DataType.choices)
    schema = models.ForeignKey('Schema', on_delete=models.CASCADE, related_name='columns')
    order = models.PositiveSmallIntegerField(default=1)

    class Meta:
        verbose_name = 'Schema column'
        verbose_name_plural = 'Schema columns'
        ordering = ['schema', 'order']

    def __str__(self):
        return self.name

    @property
    def data_have_limits(self):
        return self.data_type in self.LIMITED_DATA_TYPES

    def _get_source_data(self):
        source_types = self.DATA_TYPE_SOURCE_TYPES.get(self.data_type)
        data = {}

        if source_types is not None:
            for source_type in source_types:
                source_data_list = list(
                    SourceData.objects.filter(source_type=source_type).values_list('source_data', flat=True),
                )

                if not source_data_list:
                    raise ObjectDoesNotExist(f"Not Found Source Data with type {source_type}.")

                data.update(
                    {source_type: source_data_list},
                )

        return data

    def get_data_generator(self):
        return CellDataGenerator(
            data_type=self.DataType(self.data_type),
            have_limits=self.data_have_limits,
            minimal=self.minimal,
            maximal=self.maximal,
            source_data=self._get_source_data(),
        )

    def clean(self):
        if self.data_type in self.LIMITED_DATA_TYPES:

            if self.minimal is None or self.maximal is None:
                raise ValidationError('Limits (From and To) should both be set for this Type of column')

            if self.minimal > self.maximal:
                raise ValidationError('From should be less number then To, or equal')

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.data_have_limits:
            self.minimal = None
            self.maximal = None
        super().save()


class SourceData(models.Model):
    """Model for storing source data for generating data types, that needs source."""
    source_type = models.CharField(max_length=25, db_index=True)
    source_data = models.CharField(max_length=60)


class Schema(models.Model):
    """Represent schema, the structure of generating data sets."""
    name = models.CharField(max_length=64)
    slug = AutoSlugField(populate_from='name', unique=True)
    time_update = models.DateField(auto_now=True, verbose_name='modified')
    delimiter = models.ForeignKey('Separator', on_delete=models.PROTECT, related_name='schemas_with_delimiter')
    quotechar = models.ForeignKey('Separator', on_delete=models.PROTECT, related_name='schemas_with_quotechar')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='schemas')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('schema-data-sets', kwargs={'schema_slug': self.slug})

    def get_data_generator(self):
        return RowDataGenerator(self.columns.all())

    @property
    def column_headers(self):
        return list(map(lambda d: d['name'], self.columns.values('name')))

    def clean(self):
        # hasattr needs to avoid error, which occurs when empty data is transferred to ModelForm while testing
        if hasattr(self, 'delimiter') and hasattr(self, 'quotechar') and self.delimiter == self.quotechar:
            raise ValidationError('String character must not be the same as column separator')


class Separator(models.Model):
    """Model of separator (delimiter and quotechar) in generating csv files."""
    name = models.CharField(max_length=32)
    char = models.CharField(max_length=1, unique=True)

    def __str__(self):
        return f"{self.name} ({self.char})"


class DataSet(models.Model):
    """
    Representation of data set.
    If generating of csv file is processing: finished status is False, and it links to no file.
    If file generating was successful: finished status would be True and field 'file' contains link to csv file.
    If file generating fails: finished status would be True, but field 'file' links to no file.
    """
    time_create = models.DateField(auto_now_add=True, verbose_name="created")
    file = models.FileField(validators=[FileExtensionValidator(allowed_extensions=['csv'])], blank=True,
                            verbose_name='csv file')
    schema = models.ForeignKey('Schema', on_delete=models.CASCADE, related_name='data_sets')
    finished = models.BooleanField(default=False, verbose_name='generating csv file is finished')

    class Meta:
        verbose_name = 'Data set'
        verbose_name_plural = 'Data sets'
        ordering = ['time_create']

    def generate_file(self, rows_amount):
        generate_csv_file(self, rows_amount=rows_amount)

mainapp/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.db.models import ExpressionWrapper, Q, BooleanField
from django.http import HttpResponseRedirect, Http404, FileResponse, JsonResponse
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.http import require_GET
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.detail import SingleObjectMixin

from .base_views import base_view_for_ajax
from .forms import RegisterUserForm, LoginUserForm, SchemaForm, ColumnFormSet
from .models import Schema, DataSet, Column


class UserRegisterView(CreateView):
    """View for registering new user."""
    form_class = RegisterUserForm
    template_name = 'mainapp/auth_form.html'
    extra_context = {'title': 'Registration',
                     'button_label': 'Register'}

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('schema-list')


class UserLoginView(LoginView):
    """View for login page."""
    form_class = LoginUserForm
    template_name = 'mainapp/auth_form.html'
    extra_context = {'title': 'Login',
                     'button_label': 'Login'}

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url

        return reverse_lazy('schema-list')


def logout_user(request):
    logout(request)
    return redirect('login')


class SchemasView(LoginRequiredMixin, ListView):
    """View for page with user's schemas."""
    model = Schema
    template_name = 'mainapp/schemas.html'
    context_object_name = 'schemas'

    def get_queryset(self):
        return self.model.objects.filter(owner=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title': 'Data Schemas',
            'current_section': 'schemas',
            'schema_slugs': [schema.slug for schema in context[self.context_object_name]],
        })
        return context


class CreateSchemaView(LoginRequiredMixin, CreateView):
    """View for page with form, where user can create new schema."""
    model = Schema
    template_name = 'mainapp/schema_form.html'
    form_class = SchemaForm
    formset_class = ColumnFormSet

    def get(self, request, *args, **kwargs):
        self.formset = self.formset_class()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        self.formset = self.formset_class(self.request.POST)
        if form.is_valid() and self.formset.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.owner_id = self.request.user.pk
        self.object = form.save()
        self.formset.instance = self.object
        self.formset.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        data_types_need_limits = Column.LIMITED_DATA_TYPES
        context.update({
            'title': 'New schema',
            'formset': self.formset,
            'data_types_need_limits': data_types_need_limits,
        })
        return context


class EditSchemaView(LoginRequiredMixin, UpdateView):
    """Page with form, where user can edit one of his schemas."""
    model = Schema
    template_name = 'mainapp/schema_form.html'
    form_class = SchemaForm
    formset_class = ColumnFormSet
    slug_url_kwarg = 'schema_slug'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=self.model.objects.select_related('owner'))
        if self.object.owner != request.user:
            raise Http404

        self.formset = self.formset_class(instance=self.object)
        return self.render_to_response(self.get_context_data())

    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=self.model.objects.select_related('owner'))
        if self.object.owner != request.user:
            raise Http404

        form = self.get_form()
        self.formset = self.formset_class(self.request.POST, instance=self.object)

        if form.is_valid() and self.formset.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.formset.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        data_types_need_limits = Column.LIMITED_DATA_TYPES
        context.update({
            'title': 'Edit schema',
            'formset': self.formset,
            'data_types_need_limits': data_types_need_limits,
        })
        return context


class SchemaDataSets(LoginRequiredMixin, SingleObjectMixin, ListView):
    """
    View for page with list of previously generated data sets of specific schema.
    Also on this page user can generate new data sets of this schema, download generated schemas or delete them.
    """
    template_name = 'mainapp/schema_data_sets.html'
    slug_url_kwarg = 'schema_slug'

    def get(self, request, *args, **kwargs):
        self.object = get_object_or_404(
            Schema.objects.prefetch_related('columns').select_related('owner'),
            slug=kwargs[self.slug_url_kwarg],
        )
        if self.object.owner != request.user:
            raise Http404
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return self.object.data_sets.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context.update({
            'title': 'Data sets',
            'schema': self.object,
        })
        return context


@require_GET
@login_required
def download(request):
    """View for processing downloads generated data sets."""
    data_set = get_object_or_404(DataSet.objects.select_related('schema__owner'), pk=request.GET.get('data_set'))
    if data_set.schema.owner != request.user:
        raise Http404

    if not data_set.file:
        raise Http404

    return FileResponse(data_set.file.open(), as_attachment=True, filename=data_set.file.name)


@base_view_for_ajax(allowed_method='POST')
def delete_schema(request, schema):
    """View for deletion data set on ajax request."""
    schema_slug = schema.slug
    schema.delete()
    return JsonResponse({'deleted_schema': schema_slug})


@base_view_for_ajax(allowed_method='POST')
def generate_data_set(request, schema):
    """View for generating new data set on ajax request."""
    try:
        rows_amount = int(request.POST.get('rows'))
    except (TypeError, ValueError):
        return JsonResponse({'file_generated': False}, status=400)

    if rows_amount < 1:
        return JsonResponse({'file_generated': False}, status=400)

    data_set = DataSet.objects.create(schema=schema)
    data_set.generate_file(rows_amount)
    return JsonResponse({'file_generated': bool(data_set.file), 'data_set_id': data_set.pk})


@base_view_for_ajax(allowed_method='GET')
def get_finished_data_sets_info(request, schema):
    """
    View for monitoring current statuses of generating data sets.
    Needs if user disconnected from server and then connects again before generation of file ended.
    """
    data_sets = DataSet.objects.filter(schema=schema).\
        annotate(file_generated=ExpressionWrapper(~Q(file=''), output_field=BooleanField())).\
        values('id', 'finished', 'file_generated')

    info = {data_set['id']: {'file_generated': data_set['file_generated']}
            for data_set in data_sets if data_set['finished']}

    return JsonResponse({'info': info})

mainapp/templates/mainapp/auth_form.html
{% extends 'mainapp/base.html' %}
{% load additional_tags %}

{% block navbar %}
{% endblock %}

{% block content %}
<div class="container flex-grow-1 d-flex align-items-center justify-content-center vh-100">
    <div class="col-12 col-md-9 col-lg-7 col-xl-6">
        <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5 text-center">
                <h2 class="text-center mb-5">{{title}}</h2>
                <form method="post">
                    {% csrf_token %}

                    <!--Errors-->
                    <div class="text-danger text-center">
                        {% for error in form.non_field_errors %}
                        <p>{{ error }}</p>
                        {% endfor %}
                    </div>

                    <!--Fields-->
                    {% for field in form %}
                        <div class="form-floating mb-4{% if field.errors %} is-invalid{% endif %}">
                            {% if field.errors %}
                                {{ field|add_attrs:"is-invalid" }}
                            {% else %}
                                {{ field }}
                            {% endif %}
                            <label for="{{ field.id_for_label }}">{{field.label}}</label>
                            {% if field.errors %}
                            <div class="invalid-feedback">
                                {% for err in field.errors %}
                                <p>{{ err }}</p>
                                {% endfor %}
                            </div>
                            {% endif %}
                        </div>
                    {% endfor %}

                    <!--Submit button-->
                    <div class="d-flex justify-content-center mt-3">
                        <button class="btn btn-primary btn-lg w-50" type="submit">{{ button_label }}</button>
                    </div>

                </form>
                {% if title == 'Login' %}
                <a href="{% url 'register' %}">Register</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>

{% block navbar %}
{% include 'mainapp/navbar.html' %}
{% endblock %}

{% block content %}
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
{% block additional_scripts %}
{% endblock %}
</body>
</html>

mainapp/templates/mainapp/login.html
{% extends 'mainapp/base.html' %}
{% load additional_tags %}

{% block navbar %}
{% endblock %}

{% block content %}
<div class="container flex-grow-1 d-flex align-items-center justify-content-center vh-100">
    <div class="col-12 col-md-9 col-lg-7 col-xl-6">
        <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
                <h2 class="text-center mb-5">{{title}}</h2>
                <form method="post">
                    {% csrf_token %}

                    <!--Errors-->
                    <div class="text-danger text-center">
                        {% for error in form.non_field_errors %}
                        <p>{{ error }}</p>
                        {% endfor %}
                    </div>

                    <!--Fields-->
                    {% for field in form %}
                        <div class="form-floating mb-4{% if field.errors %} is-invalid{% endif %}">
                            {% if field.errors %}
                                {{ field|add_attrs:"is-invalid" }}
                            {% else %}
                                {{ field }}
                            {% endif %}
                            <label for="{{ field.id_for_label }}">{{field.label}}</label>
                            {% if field.errors %}
                            <div class="invalid-feedback">
                                {% for err in field.errors %}
                                <p>{{ err }}</p>
                                {% endfor %}
                            </div>
                            {% endif %}
                        </div>
                    {% endfor %}

                    <!--Submit button-->
                    <div class="d-flex justify-content-center mt-3">
                        <button class="btn btn-primary btn-lg w-50" type="submit">{{ button_label }}</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/navbar.html
<nav class="navbar bg-light navbar-expand-md sticky-top">
    <div class="container-fluid">
        <div class="collapse navbar-collapse justify-content-between mx-5">
            <div class="navbar-nav">
                <a href="{% url 'schema-list' %}" class="navbar-brand fw-bold mx-5">
                    FakeCSV
                </a>
                <a href="{% url 'schema-list' %}" class="nav-link{% if current_section == 'schemas' %} active{% endif %} px-5">
                    Schemas
                </a>
            </div>
            <div class="navbar-nav">
                <p class="navbar-text mx-3 text-secondary">Hello, <b>{{ request.user.username }}</b></p>
                <a href="{% url 'logout' %}" class="nav-link mx-3 text-secondary">Logout</a>
            </div>
        </div>
    </div>
</nav>

mainapp/templates/mainapp/schema_data_sets.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid p-5">
    <div class="row mx-5">
        <div class="col-9">
            <div class="row">
                <p>
                    <span class="h1">Sample schema</span>
                    <span class="mx-5"><a href="{% url 'edit-schema' schema_slug=schema.slug %}" class="h4 link-primary link-underline-opacity-0">Edit schema</a></span>
                </p>
            </div>
            <div class="row mt-4">
                <div class="col-9">
                    <table class="table table-bordered">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Column name</th>
                          <th scope="col">Column type</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for column in schema.columns.all %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td>{{ column.name }}</td>
                          <td>{{ column.get_data_type_display }}</td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                </div>
            </div>
            <div class="row mt-4 d-flex justify-content-between">
                <div class="col-3">
                    <h1>{{ title }}</h1>
                </div>
                <div class="col-3 d-flex justify-content-end">
                    <div>
                        <form id="post-form" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-2 d-flex align-items-center"><label for="rows-amount">Rows:</label></div>
                                <div class="col-4">
                                    <input id="rows-amount" type="number" min="1" class="form-control" name="rows-amount" required>
                                </div>
                                <div class="col-6">
                                    <button class="btn btn-success" type="submit">Generate data</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-12">
                    <table class="table table-bordered">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Created</th>
                          <th scope="col">Status</th>
                          <th scope="col">Actions</th>
                        </tr>
                      </thead>
                      <tbody id="data-sets-table-body">
                        {% for data_set in object_list %}
                        <tr>
                          <th class="data-set-row" scope="row">{{ forloop.counter }}</th>
                          <td>{{ data_set.time_create }}</td>
                          <td><span class="badge text-bg-{% if data_set.finished and data_set.file %}success">Ready{% elif data_set.finished %}danger">Failed{% else %}secondary processing-data-set-badge" id="processing-data-set-badge-id-{{ data_set.pk }}">Processing{% endif %}</span></td>
                          <td>{% if data_set.finished and data_set.file %}<a href="{% url 'download' %}?data_set={{ data_set.pk }}" class="link-primary link-underline-opacity-0">Download</a>{% endif %}</td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block additional_scripts %}

{% url 'data-set-start-generating' as data_set_start_generating_url %}
{{ data_set_start_generating_url|json_script:"data-set-start-generating-url" }}

{% url 'download' as download_url %}
{{ download_url|json_script:"download-url" }}

{% url 'get-finished-data-sets-info' as get_finished_data_sets_info_url %}
{{ get_finished_data_sets_info_url|json_script:"get-finished-data-sets-info-url" }}

{{ schema.slug|json_script:"schema-slug" }}

<script>
    const dataGeneratingUrl = JSON.parse(document.getElementById('data-set-start-generating-url').textContent);
    const downloadUrl = JSON.parse(document.getElementById('download-url').textContent);
    const schemaSlug = JSON.parse(document.getElementById('schema-slug').textContent);
    const getGeneratingDataSetIdsUrl = JSON.parse(document.getElementById('get-finished-data-sets-info-url').textContent);
</script>
<script src="{% static 'JS/data-set-generating.js' %}"></script>
<script src="{% static 'JS/track-processing-data-sets-statuses.js' %}"></script>
{% endblock %}

mainapp/templates/mainapp/schemas.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid p-5">
    <div class="row mx-5">
        <div class="col-9">
            <div class="row">
                <div class="col-6">
                    <h1>{{ title }}</h1>
                </div>
                <div class="col-6 d-flex justify-content-end">
                    <div>
                        <a href="{% url 'create-schema' %}" class="btn btn-lg btn-success">New schema</a>
                    </div>
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-12">
                    {% csrf_token %}
                    <table class="table table-bordered">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Title</th>
                          <th scope="col">Modified</th>
                          <th scope="col">Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for schema in schemas %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td><a href="{% url 'schema-data-sets' schema_slug=schema.slug %}" class="link-primary link-underline-opacity-0">{{ schema.name }}</a></td>
                          <td>{{ schema.time_update | date }}</td>
                          <td>
                              <span class="m-3"><a href="{% url 'edit-schema' schema_slug=schema.slug %}" class="link-primary link-underline-opacity-0">Edit schema</a></span>
                              <span class="m-3"><a href="#" id="link-deletion-schema-{{ schema.slug }}" class="link-danger link-underline-opacity-0">Delete</a></span>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block additional_scripts %}

{% url 'delete-schema' as delete_schema_url %}
{{ delete_schema_url|json_script:"delete-schema-url" }}

{{ schema_slugs|json_script:"schema-slugs" }}

<script>
    const schemaSlugs = JSON.parse(document.getElementById('schema-slugs').textContent);
    const deleteSchemaUrl = JSON.parse(document.getElementById('delete-schema-url').textContent);
</script>
<script src="{% static 'JS/delete-schema.js' %}"></script>
{% endblock %}